### ISSUE TITLE
[23장] 실행 컨텍스트

### ISSUE THREAD

**Issue by Ryan-TheLion** [FE-STUDY2/javascript-deep-dive#10]
23장에 대한 질문을 남기는 공간입니다.

**Comment by Ryan-TheLion** [comment]
1. window와 같은 전역객체를 사용할 수 있는 이유는 무엇일까요?
2. 이를 이용해서 타입스크립트 프로젝트를 진행시 카카오와 같은 외부 SDK(javascript API)를 타입에러없이 잘 사용할 수 있는 방법에는 무엇이 있을까요?

**Comment by jyj1111** [comment]
1. 자바스크립트 엔진이 소스코드를 처리하는 과정에 대해 설명해주세요.

**Comment by youzysu** [comment]
렉시컬 환경(LexicalEnvironment)을 스코프 체인과 연관지어 이야기해봅시다!

> 변수에 접근할 때 현재 컨텍스트의 렉시컬 환경을 탐색하고, 발견되면 그 값을 반환한다. (EnvironmentRecord)
> 발견하지 못할 경우 OuterLexicalEnvironmentReference에 담긴 LexicalEnvironment를 탐색한다.
> 전역 컨텍스트의 렉시컬환경까지 탐색해도 해당 변수를 찾지 못하면 undefined가 반환된다.

**Comment by dokimion24** [comment]
실행 컨텍스트는 어떤 역할을 하나요?

**Comment by Ryan-TheLion** [comment]
2주차 모임 완료
