### ISSUE TITLE
[9장] 타입 변환과 단축 평가

### ISSUE THREAD

**Issue by annoeul** [FE-STUDY2/javascript-deep-dive#11]
[9장] 타입 변환과 단축 평가

**Comment by Ryan-TheLion** [comment]
단축평가, 삼항 연산자 ` ? : `, 스프레드 연산자 `...` 등을 이용해서 조건에 따라 객체를 생성해서 활용하는 방법이 있을까요?

**Comment by jyj1111** [comment]
1. 논리연산자가 있음에도 불구하고 옵셔널 체이닝 연산자 하고 null 병합 연산자가 도입된 이유는 무엇인가요?

**Comment by youzysu** [comment]
false로 평가되는 Falsy 값 6가지를 말해주세요!

**Comment by annoeul** [comment]
'a' || false && 'b' 
결과값에 대해 얘기해주세요

**Comment by dokimion24** [comment]
아래 코드를 옵셔널 체이닝 연산자로 나타내주세요
```javascript
let user = {}; 
alert( user && user.address && user.address.street ); 
```

**Comment by Ryan-TheLion** [comment]
2주차 모임 완료
