### ISSUE TITLE
[12장] 함수

### ISSUE THREAD

**Issue by jyj1111** [FE-STUDY2/javascript-deep-dive#17]
1. 함수선언문과 함수표현식의 차이점에 대해 2가지 이상 설명해주세요.
2. 함수는 객체인데 일반 객체하고의 차이점에 대해 설명해주세요. 
3. 함수형 프로그래밍이란 무엇인가요?
4. 함수를 정의하는 방식은 무엇이 있나요?

**Comment by seon-mikim** [comment]
재귀 함수란 무엇인가요?
재귀 함수는 자신을 무한 재귀 호출 하는데 멈추기 위해 무엇이 필요한가?

**Comment by dokimion24** [comment]
- 함수의 매개변수와 인자는 무엇인가요?

**Comment by annoeul** [comment]
p.157 예제 12-04

**Comment by Ryan-TheLion** [comment]
함수를 사용하는 이유에 대해 생각해보고 자유롭게 의견을 나누며 소통해보는 것은 어떨까요?

**Comment by annoeul** [comment]
선언문과 표현식의 차이점에 대해 얘기해주세요

**Comment by Ryan-TheLion** [comment]
모임 완료
