### ISSUE TITLE
[1주차] 변수 질문

### ISSUE THREAD

**Issue by youzysu** [FE-STUDY2/javascript-deep-dive#2]
> ### 스터디 일정: 12/28(수) 13시

(아래 템플릿처럼 자신이 담당한 챕터에 대한 질문 2가지 작성해서 올려주시면 됩니다.)

## (예시) 13장 스코프
- 질문1: 스코프 체인과 실행 컨텍스트, 렉시컬 환경에 대해 설명해주세요.
- 질문2: 동적 스코프와 렉시컬 스코프의 차이점에 대해 설명해주세요. 자바스크립트는 어떤 스코프를 따르나요? 상위 스코프를 결정하는 기준은 무엇인가요?

**Comment by dokimion24** [comment]
## 14장 전역 변수의 문제점
---
* 질문1: 전역 변수와 지역 변수의 생명 주기에 대해 설명해주세요.
* 질문2: 전역 변수의 무분별한 사용은 어떤 문제를 가져올까요? 전역 변수의 사용을 억제하는 방법은 무엇인가요?

**Comment by dokimion24** [comment]
## 15장 let, const 키워드와 블록 레벨 스코프
---
* 질문1: TDZ(일시적 사각지대)에 대해 설명해주세요.
* 질문2: var, let 키워드로 선언한 변수는 어떤 차이점을 가지고 있는지 2가지를 말해주세요.

**Comment by youzysu** [comment]
## 13장 스코프
- 질문1: 함수의 매개변수의 스코프는?
- 질문2: 아래 코드의 실행 결과는? bar 함수의 스코프는?
```js
var x = 1;

function foo() {
  var x = 10;
  bar();
}

function bar() {
  console.log(x);
}

foo(); // ?
bar(); // ?
```

**Comment by jyj1111** [comment]
## 13장 스코프 
--- 
- 질문1: 함수 레벨스코프란 무엇인가요? 함수 레벨스코프와 블록 레벨스코프의 관점에서 var하고 let,const의 차이는?
- 질문2: 동적 스코프와 정적 스코프의 차이에 대해 설명해주세요.

**Comment by annoeul** [comment]
## 4장 변수

- 질문1 : 변수와 식별자의 차이점은?

**Comment by Ryan-TheLion** [comment]
1주차 모임 완료
