### ISSUE TITLE
[11장] 원시 값과 객체의 비교

### ISSUE THREAD

**Issue by youzysu** [FE-STUDY2/javascript-deep-dive#9]
여기에 <11장 원시 값과 객체의 비교>에 대한 질문을 올려주세요 :)

**Comment by youzysu** [comment]
자바스크립트에서 원시 값의 특성인 불변성이란 무엇인가요?

**Comment by youzysu** [comment]
객체의 가변성이 갖는 문제점은 무엇인가요?

**Comment by youzysu** [comment]
얕은 복사와 깊은 복사의 차이점은 무엇인가요?

**Comment by Ryan-TheLion** [comment]
1. `유사배열객체`란 무엇인가요?
2. `이터레이션 프로토콜(iteration protocol)`이란 무엇인가요?

**Comment by jyj1111** [comment]
1. 원시값과 객체의 차이점에 대해 설명해주세요.

**Comment by dokimion24** [comment]
결과 값은 무엇일까요?
```javascript
let a = {};
let b = {}; 
console.log(a === b);
```

**Comment by Ryan-TheLion** [comment]
2주차 모임 완료
